export enum RiskCategory {
  MARKET_LIQUIDITY = 'MARKET_LIQUIDITY',
  LEGAL_TITLE = 'LEGAL_TITLE',
  BUREAUCRACY = 'BUREAUCRACY',
  TAX_REGIME_LOCAL = 'TAX_REGIME_LOCAL',
  TAX_REGIME_ISRAEL = 'TAX_REGIME_ISRAEL',
  REGULATORY_RESTRICTIONS = 'REGULATORY_RESTRICTIONS',
  CRIMINAL_RISK = 'CRIMINAL_RISK',
  REMOTE_MANAGEMENT = 'REMOTE_MANAGEMENT',
  MAINTENANCE_COSTS = 'MAINTENANCE_COSTS',
  EXIT_STRATEGY = 'EXIT_STRATEGY',
}
